import Head from 'next/head'
import styles from '@/styles/Home.module.css'
// useState permet de créer des variables dans React
// Permet de dire ce qu'il doit se passer quand un état change
import { useState, useEffect } from "react";

export default function Home() {

  //useState permet de donner la valeur initiale de number à 12
  const [number, setNumber] = useState(12);

  // l'ordre des useEffect est important car cela s'execute dans cet ordre

  useEffect(() => {
    console.log("Un rendering a eu lieu, quelque chose a changé dans l'application")
  })

  useEffect(() => {
    console.log("La page vient de se charger")
  }, [])

  useEffect(() => {
    alert("Le nombre vient de changer")
  }, [number])

  const increment = () => {
    setNumber(number + 1)
  }

  return (
    <>
      <Head>
        <title>Increment Decrement App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <p><button onClick={() => increment()}>Increment </button></p>
        <p><button onClick={() => setNumber(number - 1)}>Decrement </button></p>
        {number}
      </div>

    </>
  )
}
